Feature
sagieramos/Hello-world pull request #1
Opened 2023-04-25 14:45 UTC by sagieramos

- Added HTML
- Added Stylesheet
- Added README

2023-04-25 15:36 UTC, joel-kalema requested changes
# STATUS: REQUIRED CHANGES :recycle::recycle: 

Hi @sagieramos 
Good job so far! I know you worked hard to implement this project, I really appreciate the effort you put in! But there are some issues that you still need to work on to go to the next project but you are almost there! 

![almost-there](https://user-images.githubusercontent.com/57562869/143511358-9cde7daf-4ad0-4db2-8f15-18b54288ff91.gif)

## To highlight :champagne: 
- All linters are passing :heavy_check_mark: 
- Good commit history :heavy_check_mark: 
- Your design looks good :100: :heavy_check_mark: 
- Good PR description :heavy_check_mark: 
- Follow GitHub flow :heavy_check_mark: 

## Required changes :recycle: :recycle: 
- [ ] Check the comments under the review.

## Optional suggestions

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

_Feel free to leave any questions or comments in the PR thread if something is not 100% clear. 
Please ping me @joel-kalema  when you comment so I can receive the notification or use slack with the same name._

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-25 15:36 UTC, joel-kalema commented on index.html
> +<head>
#### Great job working on setting up a 'Hello Microverse' project 👍. however, you need to fix some parts:

- [ ] Currently, your project doesn't have a descriptive pull request. Kindly make sure you added some information about what you have done in this project to make it more descriptive 😃

![Capture](https://user-images.githubusercontent.com/57408419/234318451-d815a53a-646b-4518-ae08-03a2e5b0a7e3.JPG)

- [ ] Currently, talking about linter, it helps us clean and standardize our code regarding best practices and DRY method, Kindly make sure you fixed then 👍 

![Capture](https://user-images.githubusercontent.com/57408419/234318993-65ac4f4b-f19e-4551-b11a-0fb84ab04c7f.JPG)

- [ ] Talking about README

 - Kindly make sure you deleted the [Microverse logo](https://github.com/sagieramos/Hello-world/tree/feature#:~:text=Microverse%20README%20Template) or you may replace with your own if you have one 😄

![Capture](https://user-images.githubusercontent.com/57408419/234321806-a7eff58b-4191-411e-b6e0-63ddac9dc94e.JPG)

  - Kindly make sure you customized the sections below, you may show how we can `Setup`, `Install`, and `Usage` your project, also, you may remove the `Run tests` and `Deployment` sections. Aloso make sure you added a `Description` for this project. Kindly fix it to make your README more descriptive 👍

![Capture](https://user-images.githubusercontent.com/57408419/234325351-b3aeccce-5ff8-4d27-ac91-32cebb68d21a.JPG)

  -  Make sure you added all information about your social media for `👤 Author1` and remove `👤 Author2`.  Kindly, fix it 👍  

![Capture](https://user-images.githubusercontent.com/57408419/234326209-9f628c6f-39f8-4303-a8ca-ee6bc2c99022.JPG)

 - Make sure your MIT license is working, you may add the like to your `MIT` file. It'll be some thing like `This project is [MIT](./MIT.md) licensed.` . Kindly fix it 👍 

![Capture](https://user-images.githubusercontent.com/57408419/234328923-64fd80f0-5c8e-495d-823f-c2d0619e9673.JPG)

2023-04-26 12:28 UTC, sagieramos commented on index.html
> +<head>
### Set up a "Hello Microverse" project
**Issues fixed**
- The README was updated. 
- A new MIT license was added.

2023-04-28 09:49 UTC, sagieramos commented
README.md was upadated accordingly

2023-04-28 10:26 UTC, divinecharlotte requested changes
Hi @sagieramos     , 

Good job so far!
You still need to work on some issues to go to the next project, but you are almost there!

## To Highlight 💯 
- linters are passing 👍





 
![](https://media.giphy.com/media/tKyrc0NTlEcGWdThp4/giphy.gif)
## Required Changes ♻️

- [ ] Kindly as requested by the previous reviewer consider adding a PR description to your pr to give more information on what you did in this branch because currently its empty

_Check the comments under the review._
## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-28 10:26 UTC, divinecharlotte commented on README.md
> +- [Live Demo Link](./index.html)
- [ ] As requested by the previous reviewer kindly consider removing this section as you are not going to deploy this project and doing so will make your readme more professional

2023-04-28 13:06 UTC, aamirkhan2478 approved these changes
Hi @sagieramos , 

![GIF](https://www.funimada.com/assets/images/cards/big/congrats-7.gif)

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
✅ You used Gitflow correctly
✅ No linter error
✅ Good commit messages
✅ Good descriptive PR
✅ Well done you did all the changes give by the previous reviewers :clap: 
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

[OPTIONAL] This is optional because the previous reviewers missed this requirement please edit your PR title it's not descriptive replace `Feature` with `Hello Microverse` and please don't skip this requirement :slightly_smiling_face: 

[OPTIONAL] This is optional because the previous reviewers missed this requirement please use a descriptive branch name. The branch name should be any action or feature like `add-heading` so kindly next time when you work on another project please keep in mind these requirements :+1: 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-02 08:43 UTC, AlphaNtihinduka approved these changes
# STATUS: APPROVED :green_circle: :clap: 
## Hi @sagieramos 🙋‍♂️, 

Your project is complete!  There is nothing else to say other than... Great job 👏 

![approved-accepted](https://user-images.githubusercontent.com/99394374/212473432-e725752b-8682-4dbb-993e-9e466dbe7acb.gif)

Congratulations! 🎉 
TO HIGHLIGHT:

- Your project is professional :heavy_check_mark: 
- Your repo is professional :heavy_check_mark: 
- Well-structured files :heavy_check_mark: 
- Professional README.md file 💯
- No linter errors :heavy_check_mark: 

Now you can merge this branch and move on :1st_place_medal: 


## Optional suggestions
- [ ] As suggested by the previous reviewer please ensure that the PR title is descriptive. This gives the PR visitors a clear understanding of what the pull request is all about. In addition, please ensure to make the branch name more descriptive to avoid project invalidations 
- Kindly refer to the inline optional suggestions made. Ensure to apply them to have a professional project that suits recruiters' needs.

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

HAPPY CODING AND GOOD LUCK WITH THE COMING ONES :crossed_fingers: :four_leaf_clover:

2023-05-02 08:52 UTC, merged